# Generated by Django 3.2.3 on 2021-08-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smulithackathon', '0003_auto_20210815_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='businesstype',
            new_name='indivtype',
        ),
    ]
